llm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from speakers import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^manager$', views.manager, name='manager'),
    url(r'^speaker/(?P<uuid>.*)/flight/(?P<flight_id>[0-9]+)/$', views.speaker_flight, name='speaker_flight'),
    url(r'^speaker/(?P<uuid>.*)/flight/(?P<flight_id>[0-9]+)/(?P<decision>[a-z]+)/$', views.speaker_flight_decision, name='speaker_flight_decision'),
    url(r'^speaker/(?P<uuid>.*)/$', views.speaker, name='speaker'),
    url(r'^admin/', include(admin.site.urls)),
]

flight_options/models.py
from django.db import models

class FlightOption(models.Model):

    def __unicode__(self):
        return "Flight Option #%s for %s" % (self.id, self.speaker)

    speaker = models.ForeignKey('speakers.Speaker')
    route_description = models.TextField(blank=True)
    # arrival
    arrival_date = models.DateTimeField(blank=True, null=True)
    arrival_observations = models.TextField(blank=True)
    # departure
    departure_date = models.DateTimeField(blank=True, null=True)
    departure_observations = models.TextField(blank=True)
    # sent
    sent = models.BooleanField(default=False)
    sent_timestamp = models.DateTimeField(blank=True, null=True)
    # seen
    seen = models.BooleanField(default=False)
    seen_timestamp = models.DateTimeField(blank=True, null=True)
    # approved
    approved = models.BooleanField(default=False)
    approved_timestamp = models.DateTimeField(blank=True, null=True)
    # approved
    rejected = models.BooleanField(default=False)
    rejected_timestamp = models.DateTimeField(blank=True, null=True)
    rejected_reason = models.TextField(blank=True)
    # meta
    criado = models.DateTimeField(blank=True, auto_now_add=True, verbose_name="Criado")
    atualizado = models.DateTimeField(blank=True, auto_now=True, verbose_name="Atualizado")
    

speakers/models.py
from django.db import models
import uuid
from django.core.urlresolvers import reverse

DOCUMENT_TYPE_CHOICES = (
    ('cpf', 'Brazilian CPF'),
    ('passport', 'Passport'),
)

class Speaker(models.Model):

    def __unicode__(self):

        return "%s (%s)" % (self.complete_name, self.email)

    def get_absolute_url(self):
        return reverse("speaker", args=[self.uuid])

    def open_flight_options(self):
        return self.flightoption_set.filter(rejected=False)

    email = models.EmailField()
    complete_name = models.CharField(blank=True, max_length=100)
    nickname = models.CharField(blank=True, max_length=100)
    document = models.CharField(blank=True, max_length=100)
    document_type = models.CharField(blank=True, max_length=100, choices=DOCUMENT_TYPE_CHOICES)
    contact_phones = models.TextField(blank=True)
    origin_city_state = models.CharField(blank=True, max_length=100)
    require_flight = models.BooleanField(default=False)
    flight_arranged = models.BooleanField(default=False)
    waiting_flight = models.BooleanField(default=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

talks/models.py
from django.db import models

class Talk(models.Model):
    speaker = models.ForeignKey('speakers.Speaker')
    titulo = models.CharField(blank=False, max_length=100)
    descricao = models.TextField(blank=False)
    aprovada = models.BooleanField(default=False)
    alocada = models.BooleanField(default=False)

flight_options/views.py
from django.shortcuts import render

# Create your views here.

speakers/views.py
import datetime
from django.shortcuts import render

from speakers.models import Speaker
from flight_options.models import FlightOption

from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.shortcuts import redirect

from django.contrib import messages

class SpeakerForm(ModelForm):
    
    def clean(self):
        cleaned_data = super(SpeakerForm, self).clean()
        document = cleaned_data.get("document")
        document_type = cleaned_data.get("document_type")
        origin_city_state = cleaned_data.get("origin_city_state")
        if self.instance.require_flight:
            if not document or not document_type or not origin_city_state:
                raise ValidationError('Error! We need some additional information in order to buy you flight tickets. Please, fill bellow.')
                
    
    def __init__(self, *args, **kwargs):
        super(SpeakerForm, self).__init__(*args, **kwargs)
        self.fields['complete_name'].required = True
        if self.instance.require_flight:
            self.fields['document'].required = True
            self.fields['document_type'].required = True
            self.fields['origin_city_state'].required = True
            
    class Meta:
        model = Speaker
        fields = "complete_name", 'nickname', 'document', 'document_type', 'contact_phones', 'origin_city_state'

def home(request):
    context = {}
    return render(request, 'index.html', context,)

def speaker(request, uuid):
    speaker = Speaker.objects.get(uuid=uuid)
    if not speaker.complete_name:
        show_first_time_modal = True
    else:
        show_first_time_modal = False
    if request.POST:
        speaker_form = SpeakerForm(request.POST, instance=speaker)
        if speaker_form.is_valid():
            updated_speaker = speaker_form.save(commit=False)
            updated_speaker.waiting_flight = True
            updated_speaker.save()
            return redirect(reverse("speaker", args=[speaker.uuid]))
        else:
            speaker = Speaker.objects.get(uuid=uuid)
            show_first_time_modal = False
    else:
        speaker_form = SpeakerForm(instance=speaker)

    context = {
        'speaker': speaker,
        'speaker_form': speaker_form,
        'show_first_time_modal': show_first_time_modal
    }
    return render(request, 'speaker.html', context,)

def speaker_flight(request, uuid, flight_id):
    flight = FlightOption.objects.get(speaker__uuid=uuid, pk=flight_id)
    if not flight.seen:
        flight.seen_timestamp = datetime.datetime.now()
        flight.seen = True
        flight.save()
    context = {
        'speaker': flight.speaker,
        'flight': flight
    }
    return render(request, 'speaker_flight.html', context,)

def speaker_flight_decision(request, uuid, flight_id, decision):
    flight = FlightOption.objects.get(speaker__uuid=uuid, pk=flight_id)
    if decision == "accept":
        messages.success(request, "Success! Flight Option ID %s Accepted" % flight.pk)
        flight.approved=True
        flight.approved_timestamp = datetime.datetime.now()
        flight.save()
    else:
        messages.error(request, "Flight Option ID %s Rejected"  % flight.pk)
        flight.rejected=True
        flight.rejected_timestamp = datetime.datetime.now()
        flight.save()
    return redirect(reverse("speaker", args=[flight.speaker.uuid]))

def manager(request):
    speakers_no_name = Speaker.objects.filter(complete_name__in=(None, ''))
    flightoptions_not_rejected_not_seen = FlightOption.objects.filter(rejected=False, seen=False)
    context = {
        'speakers_no_name': speakers_no_name,
        'flightoptions_not_rejected_not_seen': flightoptions_not_rejected_not_seen
    }
    return render(request, 'manager.html', context,)


talks/views.py
from django.shortcuts import render

# Create your views here.

speakers/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Latinoware Logistic Manager</title>

    <!-- Bootstrap core CSS -->
	{% bootstrap_css %}

  </head>

  <body>
  {% if messages %}
      <div id="alertas">
      {% for message in messages %}
          {% if message.tags == "error" %}
              <div class="alert alert-danger" role="alert">
          {% else %}
              <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
          {% endif %}
      <a class="close" data-dismiss="alert">×</a>
      {% if message.tags == "error" %}
          <i class="fa fa-times-circle-o"></i>
      {% endif %}
      {% if message.tags == "info" %}
          <i class="fa fa-comment"></i>
      {% endif %}
      {% if message.tags == "success" %}
          <i class="fa fa-check-circle"></i>
      {% endif %}
      {% if message.tags == "warning" %}
          <i class="fa fa-warning"></i>
      {% endif %}

      {{ message|safe }}
      </div>
      {% endfor %}
  </div>
  {% endif %}
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Latinoware Logistics Manager</h3>
      </div>
	  {% block body %}
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <p class="lead">This system was made to help gathering the necessary informations for Latinoware.</p>
      </div>
	  {% endblock %}


      <footer class="footer">
        <p>Latinoware 2015</p>
      </footer>

    </div> <!-- /container -->
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
    {% bootstrap_javascript %}
	{% block javascript %}
	
	{% endblock %}
  </body>
</html>

speakers/templates/index.html
{% extends "base.html" %}

speakers/templates/manager.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

    <h1>Speakers with no Name</h1>

    <ul>
    {%  for speaker in speakers_no_name %}
        <li>{{ speaker }}</li>
    {%  empty %}
        0 Spekers
    {%  endfor %}
    </ul>


    <h1>Flight Options not Rejected and not Seen</h1>

    <ul>
    {%  for flight in flightoptions_not_rejected_not_seen %}
        <li>{{ flight }}</li>
        {%  empty %}
            0 Flight Options
    {%  endfor %}
    </ul>


{% endblock %}

speakers/templates/speaker.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

<!-- Modal -->
<div class="modal fade" id="welcome-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Welcome to Latinoware!</h4>
      </div>
      <div class="modal-body">
        <p>Here we have a welcome text and an explanation about the next steps</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="row row-fluid">
    <div class="col-md-6">
        {% if speaker.complete_name %}
            <h2>Personal Informations</h2>
            <p>Email: {{speaker.email}}</p>
            <p>Complete Name: {{speaker.complete_name}}</p>
            <p>NickName: {{speaker.nickname}}</p>
            <p>Document: {{speaker.document}} ({{speaker.get_document_type_display}})</p>
            <p>Contact Phones: {{speaker.contact_phones}}</p>
            <p>Origin City and State: {{speaker.origin_city_state}}</p>
        {% else %}

        {% block javascript %}

        {% if show_first_time_modal %}
        <script>
        $( document ).ready(function() {
            $('#welcome-modal').modal('show');
        });
        {% endif %}
        </script>
        {% endblock %}

        <h1>Please, fill your data bellow:</h1>

        <form method="post">
            {% csrf_token %}
            {% bootstrap_form speaker_form %}
            {% buttons %}
              <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
              </button>
            {% endbuttons %}
        </form>
        {% endif %}
    </div>
    <div class="cold-md-6">
        {%  if speaker.require_flight and speaker.complete_name %}
        <h2>Flight Options</h2>
            <ul>
            {%  for flight in speaker.open_flight_options %}
            <li>
                {%  if not flight.seen %}
                    <b>
                {%  endif %}
                <a href="{%  url "speaker_flight" speaker.uuid flight.pk %}">Flight Option ID #{{ flight.pk }} {%  if not flight.seen %}
                    NEW!!
                {%  endif %}</a>
                 {%  if not flight.seen %}
                    </b>
                {%  endif %}
            </li>
            {% empty %}
                <i>No Flight Options. You will get noticed by email when we have it.</i>
            {%  endfor %}
            </ul>
        {%  endif %}
    </div>

</div>


{% endblock %}

speakers/templates/speaker_flight.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

<div class="row row-fluid">
    <div class="col-md-6">
            <h2>Personal Informations</h2>
            <p>Email: {{speaker.email}}</p>
            <p>Complete Name: {{speaker.complete_name}}</p>
            <p>NickName: {{speaker.nickname}}</p>
            <p>Document: {{speaker.document}} ({{speaker.get_document_type_display}})</p>
            <p>Contact Phones: {{speaker.contact_phones}}</p>
            <p>Origin City and State: {{speaker.origin_city_state}}</p>

    </div>
    <div class="col-md-6">
        <h2>Flight Option: #{{  flight.id }}</h2>
            <a href="{%  url "speaker" speaker.uuid %}">back</a><br />
            Seen: {{ flight.seen_timestamp|date:"SHORT_DATETIME_FORMAT" }}<br />
            <p class="well well-sm">
                <b>Route Description</b><br />
                {{ flight.route_description|linebreaksbr }}
            </p>
            Arrival: {{ flight.arrival_date|date:"SHORT_DATETIME_FORMAT" }} ({{ flight.arrival_description }})<br />
            Departure: {{ flight.departure_date|date:"SHORT_DATETIME_FORMAT" }} ({{ flight.departure_description }})<br />


        <p class="btn btn-group">
            {%  if not flight.approved %}
            <a class="btn btn-success" href="{%  url "speaker_flight_decision" speaker.uuid flight.pk "accept" %}">Accept</a>
            <a class="btn btn-danger" href="{%  url "speaker_flight_decision" speaker.uuid flight.pk "deny" %}" >Reject</a>
            {%  endif %}

        </p>





    </div>

</div>


{% endblock %}